#!/usr/bin/env python3
"""
Sliding-window PINN: a physics-informed surrogate that keeps the ODE OUT of
inference but uses it to REGULARIZE training.

The pure NN (nn_baseline.py) predicts next-day concentrations directly. Here the
network has TWO heads: concentrations (what we use) and fluxes v (a training-only
consistency variable). The physics loss ties them through the mechanistic ODE:

    conc_pred  should equal  closed_form_step(C_now, v_pred, cin, eta)

i.e. "the concentration you predict should be what the ODE produces when fed the
flux you predict." lambda_ode weights this. At inference we use conc_pred alone,
no ODE solver, so we keep the ~3000x speedup while staying mechanistically
constrained during training.

Why two heads: the ODE's right-hand side depends on the per-cell fluxes v, which
are a latent property of each reactor, not a function of the state. So a residual
computed from concentrations alone does not close; the network has to also
predict v for the physics term to be well defined.

NOTE ON SYNTHETIC DATA: the data here is generated BY this ODE, so the physics
loss is largely redundant with the data loss (both point at the same trajectory).
The residual's real value is for REAL data (regularize toward physics while the
data loss anchors to biology) or collocation points with no data. On synthetic we
mainly check it does not HURT fidelity and costs nothing at inference. Sweep
lambda_ode to see the trade-off.

Usage:
    python pinn_baseline.py --data synthetic_ode.npz --lambda-ode 0.1
    python pinn_baseline.py --data synthetic_ode.npz --sweep 0 0.03 0.1 0.3 1.0
"""
import argparse
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import DataLoader, TensorDataset

from device_utils import pick_device
from generate_synthetic_ode import build_windows, WINDOW_FEATURE_INDICES
from model import N_FEATURES, SEQ_LEN, N_DAYS
from model_primeur import closed_form_step, ETA_SWITCH_DAY

FEATURE_NAMES = ['CellDensity', 'CellSize', 'Titer', 'Glucose',
                 'Glutamine', 'Asparagine', 'Serine', 'Glycine']


class WindowPINN(nn.Module):
    """1D conv + attention body, two linear heads: concentrations and fluxes."""

    def __init__(self, n_features=N_FEATURES, hidden=64):
        super().__init__()
        self.n_features = n_features
        self.conv = nn.Sequential(
            nn.Conv1d(n_features + 1, hidden, 3, padding=1), nn.ReLU(),
            nn.Conv1d(hidden, hidden, 3, padding=1), nn.ReLU())
        self.attn = nn.Linear(hidden, 1)
        self.head_conc = nn.Linear(hidden, n_features)   # normalized next-day conc
        self.head_flux = nn.Linear(hidden, n_features)   # per-cell fluxes (physical)

    def forward(self, x):
        h = self.conv(x.transpose(1, 2)).transpose(1, 2)
        w = torch.softmax(self.attn(h).squeeze(-1), dim=-1)
        ctx = (h * w.unsqueeze(-1)).sum(dim=1)
        return self.head_conc(ctx), self.head_flux(ctx)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='synthetic_ode.npz')
    ap.add_argument('--lambda-ode', type=float, default=0.1)
    ap.add_argument('--sweep', type=float, nargs='+', default=None,
                    help='sweep lambda_ode values, e.g. --sweep 0 0.03 0.1 0.3 1.0')
    ap.add_argument('--epochs', type=int, default=150)
    ap.add_argument('--hidden', type=int, default=64)
    ap.add_argument('--batch', type=int, default=64)
    ap.add_argument('--lr', type=float, default=1e-3)
    ap.add_argument('--seq-len', type=int, default=SEQ_LEN)
    ap.add_argument('--val-frac', type=float, default=0.1)
    ap.add_argument('--seed', type=int, default=0)
    args = ap.parse_args()

    torch.manual_seed(args.seed); np.random.seed(args.seed)
    device = pick_device()
    seq_len = args.seq_len

    npz = np.load(args.data, allow_pickle=True)
    doe_params = npz['doe_params'].astype(np.float32)
    cin_params = npz['cin_params'].astype(np.float32)
    traj = npz['trajectories'].astype(np.float32)
    n_original = int(npz['n_original'])
    sub = traj[:, :, WINDOW_FEATURE_INDICES].astype(np.float32)   # (N, N_DAYS, 8) absolute

    # windows from the extras; keep cin + eta (needed for the physics term)
    windows, targets, _wd, wcin, weta, ridx = build_windows(
        traj[n_original:], doe_params=doe_params[n_original:],
        cin_params=cin_params[n_original:], seq_len=seq_len)
    windows = windows.astype(np.float32); targets = targets.astype(np.float32)
    wcin = wcin.astype(np.float32); weta = weta.astype(np.float32).reshape(-1, 1)

    # window-level split (reactors NOT held out)
    rng = np.random.default_rng(args.seed)
    val_mask = np.zeros(len(windows), bool)
    for r in np.unique(ridx):
        idx = np.where(ridx == r)[0]
        val_mask[rng.choice(idx, max(1, int(round(len(idx) * args.val_frac))), replace=False)] = True
    tr = ~val_mask

    wf, wt = windows[:, :, :N_FEATURES], windows[:, :, N_FEATURES:]
    scaler = MinMaxScaler().fit(np.vstack([wf[tr].reshape(-1, N_FEATURES), targets[tr]]))
    fmin = torch.tensor(scaler.data_min_, dtype=torch.float32, device=device)
    fsc  = torch.tensor(scaler.data_max_ - scaler.data_min_, dtype=torch.float32, device=device)
    fsc  = torch.where(fsc == 0, torch.ones_like(fsc), fsc)

    def norm_w(w, t):
        n, s, f = w.shape
        sc = scaler.transform(w.reshape(-1, f)).reshape(n, s, f).astype(np.float32)
        return np.concatenate([sc, t], axis=2)

    def make_ds(mask):
        return TensorDataset(
            torch.from_numpy(norm_w(wf[mask], wt[mask])),
            torch.from_numpy(scaler.transform(targets[mask]).astype(np.float32)),
            torch.from_numpy(wcin[mask]), torch.from_numpy(weta[mask]))

    tr_ld = DataLoader(make_ds(tr), batch_size=args.batch, shuffle=True)

    def run(lam):
        torch.manual_seed(args.seed)
        model = WindowPINN(hidden=args.hidden).to(device)
        opt = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
        print(f'  training lambda={lam} ...', flush=True)
        for ep in range(1, args.epochs + 1):
            model.train(); td = to = 0.0
            for x, y, cin, eta in tr_ld:
                x, y, cin, eta = x.to(device), y.to(device), cin.to(device), eta.to(device)
                opt.zero_grad()
                conc, flux = model(x)
                loss_data = ((conc - y) ** 2).mean()
                # physics: conc should match the ODE fed with the predicted flux
                C_now = x[:, -1, :N_FEATURES] * fsc + fmin                 # physical
                phys = closed_form_step(C_now, flux, cin, eta_titer=eta)   # physical next
                phys_n = (phys - fmin) / fsc                               # back to norm
                loss_ode = ((conc - phys_n) ** 2).mean()
                (loss_data + lam * loss_ode).backward(); opt.step()
                td += loss_data.item(); to += loss_ode.item()
            if ep % 20 == 0 or ep == 1:
                print(f'    epoch {ep:3d}  data={td/len(tr_ld):.5f}  '
                      f'ode={to/len(tr_ld):.5f}', flush=True)

        # eval: autoregressive rollout using the CONC head only (no ODE at inference)
        model.eval()
        fmin_np = scaler.data_min_.astype(np.float32)
        fsc_np = (scaler.data_max_ - scaler.data_min_).astype(np.float32)
        fsc_np[fsc_np == 0] = 1.0
        rows = []
        with torch.no_grad():
            for f in range(N_FEATURES):
                rhos, maes, ratios, rngs = [], [], [], []
                for i in range(n_original):
                    win = np.clip((sub[i, :seq_len] - fmin_np) / fsc_np, 0, 1)
                    tcol = (np.arange(seq_len, dtype=np.float32) / (N_DAYS - 1))[:, None]
                    win = np.concatenate([win, tcol], 1).astype(np.float32)
                    preds = []
                    for d in range(seq_len, N_DAYS):
                        xin = torch.from_numpy(win[None]).to(device)
                        c, _ = model(xin)
                        c = c.squeeze(0).cpu().numpy()
                        preds.append(c[f] * fsc_np[f] + fmin_np[f])
                        nxt = np.append(c, win[-1, N_FEATURES] + 1.0 / (N_DAYS - 1))
                        win = np.vstack([win[1:], nxt]).astype(np.float32)
                    pred = np.array(preds); real = sub[i, seq_len:, f]
                    rmax = real.max() if real.max() > 0 else 1.0
                    rngs.append((real.max() - real.min()) / rmax)
                    if np.std(pred) > 0 and np.std(real) > 0:
                        rhos.append(float(np.corrcoef(pred, real)[0, 1]))
                    maes.append(float(np.mean(np.abs(pred - real)) / rmax))
                    ratios.append(float(pred.max() / rmax))
                rows.append((FEATURE_NAMES[f], np.nanmean(rhos), np.mean(maes),
                             np.mean(ratios), np.mean(rngs)))
        return rows

    lambdas = args.sweep if args.sweep is not None else [args.lambda_ode]
    for lam in lambdas:
        rows = run(lam)
        print(f'\n=== lambda_ode = {lam} (physics-informed sliding-window PINN, '
              f'ODE only in training) ===')
        print(f'{"feature":>12} | {"rho":>5} {"normMAE":>8} {"peak":>5} {"range":>6}')
        print('-' * 46)
        for name, r, m, p, rng in rows:
            note = '  flat' if rng < 0.1 else ''
            print(f'{name:>12} | {r:>5.2f} {m:>8.3f} {p:>5.2f} {rng:>6.2f}{note}')


if __name__ == '__main__':
    main()
